### ISSUE TITLE
Logging in to cloud results in pin email

### ISSUE THREAD

**Issue by wormiedk** [natekspencer/hacs-oasis_mini#24]
If I log into the cloud in the integration I immediately receive a pin via email. Should I input this somewhere? Is there a way to validate that cloud is logged in okay?

**Comment by natekspencer** [comment]
This integration does not support validating your email, which is what the pin is used for. You'll first need to login to cloud on the official app and enter the pin there. After that, a pin should no longer be required.

**Comment by wormiedk** [comment]
Ah. I was originally logged in using google on the phone. It helped to logout and then log in again using mail. Thanks!
