### ISSUE TITLE
Led not staying off 

### ISSUE THREAD

**Issue by Booker316** [natekspencer/hacs-oasis_mini#36]
I can’t seem to get the LED to turn off and stay off. Both in a card or an automation. Otherwise I’m so happy to have this integration. Thanks.

**Comment by natekspencer** [comment]
Do you have any automations that might inadvertently be turning it back on? If not, you'll want to enable debug logs and toggle the light to see if there is something funky, but that would be weird unless you're on some unique firmware or have a very spotty connection to your oasis

**Comment by Booker316** [comment]
> Do you have any automations that might inadvertently be turning it back on? If not, you'll want to enable debug logs and toggle the light to see if there is something funky, but that would be weird unless you're on some unique firmware or have a very spotty connection to your oasis

Omg I think I know what it is. I bet it’s my motion sensor. I feel dumb. Thank you so much.
