### ISSUE TITLE
Any possibility of being able to adjust the light properties with this integration?

### ISSUE THREAD

**Issue by DanDixon** [natekspencer/hacs-oasis_mini#40]
I'd love to be able to set the light colors to match my room lights from home assistant.

Is that even possible with the API ?

Thanks for creating this integration, btw. I just got it set up, and it's pretty great.

**Comment by natekspencer** [comment]
You can actually already do exactly this! You should have an "Oasis Mini LED" light entity.
<img width="575" alt="Screenshot 2024-11-20 at 19 19 35" src="https://github.com/user-attachments/assets/e15d82c4-518d-4306-9d7f-15d9405ff133">

**Comment by DanDixon** [comment]
For some reason, I thought that only the toggle on/off worked.

Thank you!
